# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-


top = "../.."

def build(bld):
  module = bld.env.MODULE_NAME
  objects = "nacapp-{module}-objects".format(**locals())
  if bld.env['WITH_TESTS']:
    bld(
      source=bld.path.ant_glob(['**/*.cc', 
                                '**/*.cpp',
                                ]),
      target="../unit_tests", 
      features="cxx cxxprogram",
      use="NDN_CXX nacapp-share " + objects,
      includes = ["."]
    )